# Generated by Django 4.2.7 on 2024-03-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0003_kruzok'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='kruzok',
            field=models.ManyToManyField(blank=True, to='skola.kruzok'),
        ),
    ]
