# Generated by Django 4.2.7 on 2024-04-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0005_alter_kruzok_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucitel',
            name='obec',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ucitel',
            name='psc',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='ucitel',
            name='ulica',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
