# Generated by Django 5.0.1 on 2024-04-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0006_ucitel_obec_ucitel_psc_ucitel_ulica'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='datum_narodenia',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='rok_narodenia',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='vek',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ucitel',
            name='datum_narodenia',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ucitel',
            name='rok_narodenia',
            field=models.IntegerField(null=True),
        ),
    ]
