# Generated by Django 5.0.1 on 2024-03-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testovac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='High_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Priklad',
        ),
    ]
